carts/urls.py
from django.urls import path
from carts import views


app_name = 'carts'


urlpatterns = [
    path('cart_page/', views.cart_page_view, name='cart_page'),
    path('add_to_cart/<int:product_id>/', views.add_product_to_cart, name='add_cart'),
    path('remove_from_cart/<int:product_id>/', views.remove_product_from_cart, name='remove_cart'),
    path('delete_from_cart/<int:product_id>/', views.delete_product_from_cart, name='delete_cart'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('category/', include('category.urls')),
    path('account/', include('accounts.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
]


# serving media. when DEBUG = True

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

home/urls.py
from django.urls import path
from home import views


app_name = 'home'


urlpatterns = [
    path('', views.home_view, name='home'),
]

store/urls.py
from django.urls import path
from store import views


app_name = 'store'


urlpatterns = [
    path('store_page/', views.store_page_view, name='store_page'),
    path('store_page/<slug:category_slug>/', views.store_page_view, name='product_by_category'),
    path('store_page/<slug:category_slug>/<slug:selected_product_slug>/', views.product_details_page, name='product_details'),
    path('search/', views.search_functionality_view, name='search'),
]

templates/includes/footer.html
{% load static %}

<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2019 Company name </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">info@pixsellz.io</span>
				<span  class="px-2">+879-332-9375</span>
				<span  class="px-2">Street name 123, Avanue abc</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

</body>
</html>

templates/includes/links.html
{% load static %}

<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>E-cart | Online Shopping Platform</title>

<link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src="{% static 'js/script.js' %}" type="text/javascript"></script>

<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

}); 
// jquery end
</script>

</head>

templates/includes/navbar.html
{% load static %}


<body>

<header class="section-header">

    <!-- top bar -->
<nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
<div class="container">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTop4">
    <ul class="navbar-nav mr-auto">
    	<li class="nav-item dropdown">
		 	<a href="#" class="nav-link">   English </a>
		    
		</li>
		<li class="nav-item dropdown">
			<a href="#" class="nav-link"> USD </a>
		</li>
    </ul>
    <ul class="navbar-nav">
		<li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
		<li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
	</ul> 
  </div> 
</div>
</nav>


    <!-- navbar -->

<section class="header-main border-bottom">

	<div class="container">
        <div class="row align-items-center">
	        <div class="col-lg-2 col-md-3 col-6">
		        <a href="{% url 'home:home' %}" class="brand-wrap">
			        <img class="logo" src="{% static '/images/logo.png' %}">
		        </a> 
	        </div>

            <div class="col-lg col-sm col-md col-6 flex-grow-0">
                <div class="category-wrap dropdown d-inline-block float-right">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> 
                        <i class="fa fa-bars"></i> All category 
                    </button>
                    <div class="dropdown-menu">
                        {% for category in menu_links %}
                            <a class="dropdown-item" href="{% url 'store:product_by_category' category.slug %}">{{ category.category_name }}</a>
                        <!-- or -->
                        <!-- <a class="dropdown-item" href="{{ category.get_urls }}">{{ category.category_name }}</a> -->
                        {% endfor %}
                    </div>
                </div>  
            </div> 

	    <a href="{% url 'store:store_page' %}" class="btn btn-outline-primary">Store</a>

        <div class="col-lg  col-md-6 col-sm-12 col">
            <!-- search functionality -->
            <form action="{% url 'store:search' %}" class="search" method='GET'>
                <div class="input-group w-100">
                    <input type="text" class="form-control" style="width:60%;" placeholder="Search" name="keyword">
                    
                    <div class="input-group-append">
                    <button class="btn btn-primary" type="submit">
                        <i class="fa fa-search"></i>
                    </button>
                    </div>
                </div>
            </form> 
        </div> 


        <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
            <div class="d-flex justify-content-end mb-3 mb-lg-0">

                <div class="widget-header">
                    <small class="title text-muted">Welcome guest!</small>
                    <div> 
                        <a href="./signin.html">Sign in</a> <span class="dark-transp"> | </span>
                        <a href="./register.html"> Register</a>
                    </div>
                </div>

                <a href="{% url 'carts:cart_page' %}" class="widget-header pl-3 ml-3">
                    <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                    <span class="badge badge-pill badge-danger notify">{{ cart_product_count }}</span>
                </a>
            </div> 
        </div> 
    </div> 
</div> 
</section> 

</header> 