carts/urls.py
from django.urls import path
from carts import views


app_name = 'carts'


urlpatterns = [
    path('cart_page/', views.cart_page_view, name='cart_page'),
    path('add_to_cart/<int:product_id>/', views.add_product_to_cart, name='add_cart'),
    path('remove_from_cart/<int:product_id>/', views.remove_product_from_cart, name='remove_cart'),
    path('delete_from_cart/<int:product_id>/', views.delete_product_from_cart, name='delete_cart'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('category/', include('category.urls')),
    path('account/', include('accounts.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
]


# serving media. when DEBUG = True

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

store/urls.py
from django.urls import path
from store import views


app_name = 'store'


urlpatterns = [
    path('store_page/', views.store_page_view, name='store_page'),
    path('store_page/<slug:category_slug>/', views.store_page_view, name='product_by_category'),
    path('store_page/<slug:category_slug>/<slug:selected_product_slug>/', views.product_details_page, name='product_details'),
    path('search/', views.search_functionality_view, name='search'),
]

carts/models.py
from django.db import models
from store.models import Product, ProductVariation

# Create your models here.

class Cart(models.Model):

    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)


    def __str__(self):
        return self.cart_id
    




class CartItem(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(ProductVariation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)


    def sub_total(self):
        return self.product.product_price * self.quantity


    def __str__(self):
        return self.product.product_name
    

    

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from utils.user_session import _user_session_id
from store.models import Product, ProductVariation
from carts.models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def cart_page_view(request, total=0, quantity=0, cart_items=None):

    html_template_name = 'carts/cart.html'

    try:
        get_user_session_id = Cart.objects.get(cart_id=_user_session_id(request))
        cart_items = CartItem.objects.filter(cart=get_user_session_id, is_active=True)

        for item in cart_items:
            total += (item.product.product_price * item.quantity)
            quantity += item.quantity

        # applying 2% of tax in total purchase
        tax_amount = (2 * total) / 100
        pay_amount = total + tax_amount


    except ObjectDoesNotExist:
        pass
    
    context = {
        'total_price': total,
        'quantity': quantity,
        'cart_product_info': cart_items,
        'tax' : tax_amount,
        'total_pay' : pay_amount,
    }

    return render(request, html_template_name, context)




def add_product_to_cart(request, product_id):


    product_variation_list = []
    product = Product.objects.get(pk=product_id)

    if request.method == 'POST':
        
        for data in request.POST:
            key = data
            value = request.POST[key]

            try:
                get_product_variation = ProductVariation.objects.get(product=product, product_variation__iexact=key, variation_value__iexact=value)
                product_variation_list.append(get_product_variation)
            except:
                pass



    try:
        user_session = Cart.objects.get(cart_id=_user_session_id(request))

    except Cart.DoesNotExist:
        user_session = Cart.objects.create(
            cart_id = _user_session_id(request)
        )
    user_session.save()


    try:
        cart_item = CartItem.objects.get(product=product, cart=user_session)
        cart_item.quantity += 1
        cart_item.save()

    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product = product,
            cart = user_session,
            quantity = 1
        ) 
        cart_item.save()

    return redirect('carts:cart_page')





def remove_product_from_cart(request, product_id):
    
    get_user_session_id = Cart.objects.get(cart_id=_user_session_id(request))
    get_product = get_object_or_404(Product, pk=product_id)

    cart_item = CartItem.objects.get(product=get_product, cart=get_user_session_id)

    if cart_item.quantity > 1 :
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()

    return redirect('carts:cart_page')








def delete_product_from_cart(request, product_id):
    
    get_user_session_id = Cart.objects.get(cart_id=_user_session_id(request))
    get_product = get_object_or_404(Product, pk=product_id)
    cart_item = CartItem.objects.get(product=get_product, cart=get_user_session_id)
    cart_item.delete()

    return redirect('carts:cart_page')

templates/carts/cart.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


</header> <!-- section-header.// -->


<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->

{% if not cart_product_info %}

<h3>Your Shopping Cart Is Empty</h3>

<br>

<div class='text-center'>
	<a href="{% url 'store:store_page' %}" class="btn btn-primary">Continue Shopping</a>
</div>

{% else %}

<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>

{% for info in cart_product_info %}
	
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{ info.product.product_img.url }}" class="img-sm"></div>
			<figcaption class="info">
				<a href="{{ info.product.get_urls }}" class="title text-dark">{{ info.product.product_name }}</a>
				<p class="small text-muted">Version: CUH-ZCT2E  <br> Brand: Sony</p>
			</figcaption>
		</figure>
	</td>
	<td> 
		<!-- col.// -->
					<div class="col"> 
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
							<a href="{% url 'carts:remove_cart' info.product.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
							</div>
							<input type="text" class="form-control"  value="{{ info.quantity }}">
							<div class="input-group-append">
							<a href="{% url 'carts:add_cart' info.product.id %}" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-plus"></i> </a>
							</div>
						</div> <!-- input-group.// -->
					</div> <!-- col.// -->
	</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price">${{ info.sub_total }}</var> 
			<small class="text-muted"> ${{ info.product.product_price }} each</small> 
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
		<a href="{% url 'carts:delete_cart' info.product.id %}" class="btn btn-danger"> Remove</a>
	</td>
</tr>

{% endfor %}

</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">${{ total_price }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> ${{ tax }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>${{ total_pay }}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static "images/misc/payments.png" %}" height="26">
			</p>
			<a href="./place-order.html" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'store:store_page' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->

{% endif %}
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}