carts/urls.py
from django.urls import path
from carts import views


app_name = 'carts'


urlpatterns = [
    path('cart_page/', views.cart_page_view, name='cart_page'),
    path('add_to_cart/<int:product_id>/', views.add_product_to_cart, name='add_cart'),
    path('remove_from_cart/<int:product_id>/', views.remove_product_from_cart, name='remove_cart'),
    path('delete_from_cart/<int:product_id>/', views.delete_product_from_cart, name='delete_cart'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('category/', include('category.urls')),
    path('account/', include('accounts.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
]


# serving media. when DEBUG = True

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

store/urls.py
from django.urls import path
from store import views


app_name = 'store'


urlpatterns = [
    path('store_page/', views.store_page_view, name='store_page'),
    path('store_page/<slug:category_slug>/', views.store_page_view, name='product_by_category'),
    path('store_page/<slug:category_slug>/<slug:selected_product_slug>/', views.product_details_page, name='product_details'),
    path('search/', views.search_functionality_view, name='search'),
]

store/models.py
from django.db import models
from category.models import Categories
from django.urls import reverse

# Create your models here.

class Product(models.Model):

    product_name = models.CharField(max_length=50)
    product_slug = models.SlugField(max_length=100)
    product_description = models.TextField(blank=True)
    product_price = models.IntegerField()
    product_img = models.ImageField(upload_to='photos/products')
    product_stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    
    category = models.ForeignKey(Categories, on_delete=models.PROTECT)
    
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now_add=True)


    def get_urls(self):
        return reverse('store:product_details', args=[self.category.slug, self.product_slug])


    def __str__(self):
        return self.product_name
    












class VariationManager(models.Manager):

    def color_selected(self):
        return super(VariationManager, self).filter(product_variation='color', is_available=True)
    

    def size_selected(self):
        return super(VariationManager, self).filter(product_variation='size', is_available=True)




PRODUCT_VARIATIONS = [
    ('color', 'color'),
    ('size', 'size'),
]

class ProductVariation(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_variation = models.CharField(max_length=10, choices=PRODUCT_VARIATIONS)
    variation_value = models.CharField(max_length=50)
    is_available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)


    # set custom manager
    objects = VariationManager()


    def __str__(self):
        return self.product.product_name

    




    


    

store/views.py
from django.shortcuts import render, get_object_or_404
from store.models import Product
from category.models import Categories
from carts.models import CartItem
from utils.user_session import _user_session_id
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q

# Create your views here.

# store page
def store_page_view(request, category_slug=None):

    html_template_name = 'store/store.html'    

    selected_category = None
    all_product = None

    if category_slug != None:
        selected_category = get_object_or_404(Categories, slug=category_slug)
        all_product = Product.objects.filter(category=selected_category, is_available=True).order_by('id')
        
        # paginator functionality
        paginator = Paginator(all_product, 6)
        page = request.GET.get('page')
        set_page = paginator.get_page(page)

        product_count = all_product.count()

    else:
        all_product = Product.objects.all().filter(is_available = True).order_by('id')
        
        # paginator functionality
        paginator = Paginator(all_product, 6)
        page = request.GET.get('page')
        set_page = paginator.get_page(page)

        product_count = all_product.count()

    context = {
        'products': set_page,
        'count': product_count,
    }

    return render(request, html_template_name, context)









# product details
def product_details_page(request, category_slug, selected_product_slug):
    
    html_template_name = 'store/product_details.html'

    try:
        single_product = Product.objects.get(category__slug=category_slug, product_slug=selected_product_slug)
        cart_empty_or_not = CartItem.objects.filter(cart__cart_id=_user_session_id(request), product=single_product).exists()
    except Exception as err:
        raise err

    context = {
        'product_info' : single_product,
        'is_cart_available': cart_empty_or_not,
    }

    return render(request, html_template_name, context)








def search_functionality_view(request):

    html_template_name = 'store/store.html'

    if 'keyword' in request.GET:
        keyword = request.GET['keyword']

        if keyword is not " ":
            searched_product = Product.objects.order_by('-created_date').filter(Q(product_description__icontains=keyword) | Q(product_name__icontains=keyword))
            found_product = searched_product.count()
    context = {
        'products' : searched_product,
        'count': found_product,
    }

    return render(request, html_template_name, context)

templates/store/product_details.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
    <article class="gallery-wrap"> 
        <div class="img-big-wrap">
           <a href="#"><img src="{{ product_info.product_img.url }}"></a>
        </div> <!-- img-big-wrap.// -->
        
    </article> <!-- gallery-wrap .end// -->
            </aside>
            <main class="col-md-6 border-left">

  <form action="{% url 'carts:add_cart' product_info.id %}" method="POST">
    {% csrf_token %}

    <article class="content-body">
    
    <h2 class="title">{{ product_info.product_name }}</h2>
    
    <div class="mb-3"> 
        <var class="price h4">${{ product_info.product_price }}</var> 
    </div> 
    
    <p>{{ product_info.product_description }}</p>
    
    
    <hr>
        <div class="row">
            <div class="item-option-select">
                <h6>Choose Color</h6>
                <select name="color" class="form-control" required>
                  <option value="" disabled selected>Select Color</option>
                  <!-- accessing 'ProductVariation' model via 'Product' model -->
                  {% for data in product_info.productvariation_set.color_selected %}
                  <option value="{{ data.variation_value | lower }}">{{ data.variation_value | capfirst }}</option>
                  {% endfor %}
                </select>
            </div>
        </div> <!-- row.// -->
        <div class="row">
            <div class="item-option-select">
                <h6>Select Size</h6>
                <select name="size" class="form-control" required>
                  <option value="" disabled selected>Select Size</option>
                  {% for data in product_info.productvariation_set.size_selected %}
                  <option value="{{ data.variation_value | lower}}">{{ data.variation_value | capfirst }}</option>
                  {% endfor %}
                </select>
            </div>
        </div> <!-- row.// -->
        <hr>

        {% if product_info.product_stock <= 0 %}
          <h5 class='text-danger'>Out Of Stock</h5>
        {% else %}
          {% if is_cart_available %}
          <a href="{% url 'carts:cart_page' %}" class="btn  btn-success"> <span class="text">Already In Cart</span> <i class="fas fa-check"></i></a>
          {% else %}
          <button type="submit" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i></button>
          {% endif %}
        {% endif %}

    </article> <!-- product-info-aside .// -->
  </form>
            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    <br>
    
    <div class="row">
                <div class="col-md-9">
    
        <header class="section-heading">
            <h3>Customer Reviews </h3>  
            
        </header>
    
        <article class="box mb-3">
            <div class="icontext w-100">
                <img src="./images/avatars/avatar1.jpg" class="img-xs icon rounded-circle">
                <div class="text">
                    <span class="date text-muted float-md-right">24.04.2020 </span>  
                    <h6 class="mb-1">Mike John </h6>
                    
                </div>
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <p>
                    Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip
                </p>	
            </div>
        </article>
    
        
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock %}

templates/store/store.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
    <div class="container">
        {% if 'search' in request.path %}
        <h2 class="title-page">Search Results</h2>
        {% else %}
        <h2 class="title-page">Our Store</h2>
        {% endif %}

    </div> <!-- container //  -->
    </section>
    <!-- ========================= SECTION INTRO END// ========================= -->
    
    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">
    <div class="container">
    
    <div class="row">
        <aside class="col-md-3">
            
    <div class="card">
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Categories</h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_1" style="">
                <div class="card-body">
                    
                    <ul class="list-menu">
                    {% for category in menu_links %}
                        <li><a href="{{ category.get_urls }}">{{ category.category_name }}</a></li>
                    {% endfor %}
                    </ul>
    
                </div> <!-- card-body.// -->
            </div>
        </article> <!-- filter-group  .// -->
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Sizes </h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_4" style="">
                <div class="card-body">
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> XS </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> SM </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> LG </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> XXL </span>
                  </label>
            </div><!-- card-body.// -->
            </div>
        </article> <!-- filter-group .// -->
        
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Price range </h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_3" style="">
                <div class="card-body">
                    
                    <div class="form-row">
                    <div class="form-group col-md-6">
                      <label>Min</label>
                      <!-- <input class="form-control" placeholder="$0" type="number"> -->
                          <select class="mr-2 form-control">
                            <option value="0">$0</option>
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                        </select>
                    </div>
                    <div class="form-group text-right col-md-6">
                      <label>Max</label>
                          <select class="mr-2 form-control">
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                            <option value="2000">$2000+</option>
                        </select>
                    </div>
                    </div> <!-- form-row.// -->
                    <button class="btn btn-block btn-primary">Apply</button>
                </div><!-- card-body.// -->
            </div>
        </article> <!-- filter-group .// -->
        
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <main class="col-md-9">
    
    <header class="border-bottom mb-4 pb-3">
            <div class="form-inline">
                <span class="mr-md-auto"><b>{{ count }}</b> Items found </span>
                
            </div>
    </header><!-- sect-heading -->
    
    <div class="row">

        {% for product in products %}
        <div class="col-md-4">
            <figure class="card card-product-grid">
                <div class="img-wrap"> 
                    <img src="{{ product.product_img.url }}">
                    
                </div> <!-- img-wrap.// -->
                <figcaption class="info-wrap">
                    <div class="fix-height">
                        <a href="{{ product.get_urls }}" class="title">{{ product.product_name }}</a>
                        <div class="price-wrap mt-2">
                            <span class="price">${{ product.product_price }}</span>
                        </div> <!-- price-wrap.// -->
                    </div>
                    <a href="{{ product.get_urls }}" class="btn btn-block btn-primary">View Details</a>	
                </figcaption>
            </figure>
        </div> <!-- col.// -->
        {% endfor %}

    </div> <!-- row end.// -->
    
    
    <nav class="mt-4" aria-label="Page navigation sample">
        {% if products.has_other_pages %}
        <ul class="pagination">

            <!-- previous button -->
            {% if products.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            {% endif %}

            <!-- page numbers -->
            {% for page_number in products.paginator.page_range %}
                {% if products.number == page_number %}
                    <li class="page-item active"><a class="page-link" href="#">{{ page_number }}</a></li>
                {% else%}
                    <li class="page-item"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
                {% endif %}
            {% endfor %}



            <!-- next button -->
            {% if products.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
        </ul>
      {% endif %}
    </nav>
    
        </main> <!-- col.// -->
    
    </div>
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock %}